"use client"
import './globals.css'
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const queryClient = new QueryClient();// Create a client

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nursinf Record',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
